<?php

return[
    'userprofile' => 'My Profile',
    'profileinfo' => 'View and Edit your own profile information',
    'profile' => 'Profile',
    'pm' => 'Private Messages',
    'settings' => 'Settings',
    'security' => 'Security',
    'friendlist' => 'Friendlist',
    'blacklist' => 'Blacklist',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'admin' => 'Admin',
    'edit' => 'Edit',
    'validate' => 'Validate',
    'remove' => 'Remove',
    'mycharacterlist' => 'My Characters',
    'charactername' => 'Character Name',
    'actions' => 'Actions',
    'loginsucefully' => 'Well done! You are logged in! Now enjoy it!',
    'translations' => 'Translations',
    'verifymail' => 'Verify Mail Adress',
];