<?php

return [
    'name' => 'Name',
    'gender' => 'Geschlecht',
    'race' => 'Rasse',
    'tribe' => 'Stamm',
    'screenshots' => 'Screenshots',
    'birthday' => 'Geburtstag',
    'grandcompanyname' => 'Staatliche Gesellschaft',
    'freecompany' => 'Freie Gesellschaft',
    'NotA' => 'Nicht verfügbar',
    'class' => 'Klasse',
    'bio' => 'Biographie',
    'info_button' => 'Charakterinformation',
    'portrait' => 'Portrait',
    'classjobs' => 'Klassen/Jobs',
    'mounts' => 'Reittiere',
    'minions' => 'Begleiter',
    'archievments' => 'Errungenschaften',
    'classicon' => 'Klassensymbol',
    'classname' => 'Klasse/Job Name',
    'classlevel' => 'Level',
    'submitscreenshot' => 'Screenshot hinzufügen',
    'grandcompany0' => 'Keine',
    'grandcompany1' => 'Mahlstrom',
    'grandcompany3' => 'Legion der Unsterblichen',
    'grandcompany2' => 'Bruderschaft der Morgenviper',
    'parsedate' => 'Zuletzt aktualisiert am'
];