<?php

return [
    'name' => 'Name',
    'gender' => 'Geschlecht',
    'race' => 'Rasse',
    'tribe' => 'Tribe',
    'screenshots' => 'Screenshots',
    'birthday' => 'Birthday',
    'grandcompanyname' => 'Grand Company',
    'freecompany' => 'Free Company',
    'NotA' => 'Not Avaible',
    'class' => 'Class',
    'bio' => 'Biographie',
    'info_button' => 'Character Info',
    'portrait' => 'Portrait',
    'classjobs' => 'Classes/Jobs',
    'mounts' => 'Mounts',
    'minions' => 'Minions',
    'archievments' => 'Archievments',
    'classicon' => 'Class/Job Symbol',
    'classname' => 'Class/Job Name',
    'classlevel' => 'Level',
    'submitscreenshot' => 'Submit a new Screenshot',
    'grandcompany0' => 'None',
    'grandcompany1' => 'Maelstrom',
    'grandcompany3' => 'Immortal Flames',
    'grandcompany2' => 'Order of the Twin Adder',
    'parsedate' => 'Last Updated'
];