<?php

return [
    'name' => '名前',
    'gender' => '性別',
    'race' => '種族',
    'tribe' => '部族',
    'screenshots' => 'スクリーンショット',
    'birthday' => '誕生日',
    'grandcompanyname' => 'グランドカンパニー',
    'freecompany' => 'フリーカンパニー',
    'NotA' => '利用できません',
    'class' => 'Class',
    'bio' => 'Biographie',
    'info_button' => 'キャラクター情報',
    'portrait' => 'Portrait',
    'classjobs' => 'Classes/Jobs',
    'mounts' => 'Mounts',
    'minions' => 'Minions',
    'archievments' => 'Archievments',
    'classicon' => 'Class/Job Symbol',
    'classname' => 'Class/Job Name',
    'classlevel' => 'Level',
    'submitscreenshot' => 'Submit a new Screenshot',
    'grandcompany0' => 'None',
    'grandcompany1' => 'Maelstrom',
    'grandcompany3' => 'Immortal Flames',
    'grandcompany2' => 'Order of the Twin Adder',
    'parsedate' => 'Last Updated'
];