<?php

return [
    'name' => 'Nom',
    'gender' => 'Sexe',
    'race' => 'Race',
    'tribe' => 'Tribu',
    'screenshots' => "Captures d'écran",
    'birthday' => 'Anniversaire',
    'grandcompanyname' => 'Grand Company',
    'freecompany' => 'Compagnie Libre',
    'NotA' => 'Indisponible',
    'class' => 'Classe',
    'bio' => 'Biographie',
    'info_button' => 'Info Personnage',
    'portrait' => 'Portrait',
    'classjobs' => 'Classes/Jobs',
    'mounts' => 'Montures',
    'minions' => 'Mascottes',
    'archievments' => 'Hauts-Faits',
    'classicon' => 'Symbole',
    'classname' => 'Nom de la Classe/Job',
    'classlevel' => 'Niveau',
    'submitscreenshot' => "Envoyer une nouvelle capture d'écran",
    'grandcompany0' => 'Aucune',
    'grandcompany1' => 'Maelstrom',
    'grandcompany3' => 'Immortels',
    'grandcompany2' => 'Ordre des Deux Vipères',
    'parsedate' => 'Mis à jour le'
];