<?php

return [
    'name' => '名前',
    'gender' => '性別',
    'race' => '種族',
    'tribe' => '部族',
    'screenshots' => 'スクリーンショット',
    'birthday' => '誕生日',
    'grandcompanyname' => 'グランドカンパニー',
    'freecompany' => 'フリーカンパニー',
    'NotA' => '利用できません',
    'class' => 'クラス',
    'bio' => 'バイオグラフィー',
    'info_button' => 'キャラクター情報',
    'portrait' => '肖像画',
    'classjobs' => 'クラス・ジョプ',
    'mounts' => 'マウント',
    'minions' => 'ミニオン',
    'archievments' => 'アチープメント',
    'classicon' => 'クラス・ジョプ シンボル',
    'classname' => 'クラス・ジョプ 名前',
    'classlevel' => 'レベル',
    'submitscreenshot' => '新しいスクリーンショットを提出する',
    'grandcompany0' => '何もない',
    'grandcompany1' => '黒渦団',
    'grandcompany3' => '不滅隊',
    'grandcompany2' => '双蛇党',
    'parsedate' => '最終更新日'
];